notifications:
  email: false

language: node_js
node_js:
  - 14

sudo: required

services:
  - docker
  - zmq

before_install:
  - git clone https://github.com/zeromq/libzmq.git
  - cd libzmq
  - ./autogen.sh
  - ./configure --with-libsodium && make
  - sudo make install
  - sudo ldconfig
  - docker run -dit --name emscripten --user "$(id -u):$(id -g)" -v $(pwd):/src trzeci/emscripten:1.39.11-upstream bash

before_script:
  - docker exec -it emscripten make wasm

# script:
#   - ls -la
#   - ls -la out
#   - whoami



# - docker run -dit --name dtest -v $(pwd):/src esromneb/simple-clang bash
# - docker exec -it dtest make -C src test